In [1]:
import numpy as np

In [8]:
#곱셈노드
class ComputeGraph: #MulGraph
    def __init__(self):
        self.x = None
        self.y = None
        
    def forward(self,x,y):
        self.x = x
        self.y = y
        
        out = x*y
        return out
    
    def backward(self,dout):
        dx = dout*self.y
        dy = dout*self.x
        
        return dx,dy

In [9]:
apple_price = 100
apple_number = 2

cal_graph = ComputeGraph()
cal_graph.forward(apple_price,apple_number)

200

In [10]:
dout = 1
cal_graph.backward(dout)

(2, 100)

In [26]:
#사과 세금계산
price = 100
number = 2
tax = 1.1

cal_apple = ComputeGraph()
cal_tax = ComputeGraph()
apple_price = cal_apple.forward(price,number)
total_price = cal_tax.forward(apple_price,tax)

In [27]:
apple_price

200

In [28]:
total_price

220.00000000000003

In [32]:
dout = 1
dnumber, dprice = cal_apple.backward(dout)
dapple_price, dtax = cal_tax.backward(dout)

In [37]:
total_price

220.00000000000003

In [33]:
dapple_price

1.1

In [34]:
dtax

200

In [38]:
dout = dapple_price
dapple, dnumber = cal_apple.backward(dout)

In [39]:
dapple

2.2

In [40]:
dnumber

110.00000000000001

In [74]:
#덧셈노드
class AddGraph:
    def __init__(self):
        pass
        
    def forward(self,x,y):
        out = x+y
        return out
    
    def backward(self,dout):
        dx = dout*1
        dy = dout*1        
        return dx,dy

In [75]:
x1 = 5
x2 = 3
x3 = 4
f1 = AddGraph()
f2 = AddGraph()
part_sum = f1.forward(x1,x2)
total_sum = f2.forward(part_sum,x3)

In [78]:
dout = 1
df1, dx3 = f2.backward(dout)

In [82]:
total_sum

12

In [80]:
df1

1

In [81]:
dx3

1

### 문제

In [83]:
apple =100
apple_num = 2
orange = 150
orange_num = 3
tax = 1.1

In [107]:
class MulLayer:
    def __init__(self):
        self.x = None
        self.y = None
    def forward(self,x,y):
        self.x = x
        self.y = y
        out = x*y
        return out
    def backward(self,dout):
        dx = dout*self.y
        dy = dout*self.x
        return dx,dy
    
class AddLayer:
    def __init__(self):
        pass
    def forward(self,x,y):
        out = x+y
        return out
    def backward(self,dout):
        dx = dout*1
        dy = dout*1
        return dx,dy

In [124]:
mul_apple_layer = MulLayer()
mul_orange_layer = MulLayer()
mul_tax_layer = MulLayer()
add_apple_layer = AddLayer()
add_orange_layer = AddLayer()
add_tax_layer = AddLayer()
add_apple_orange_layer = AddLayer()

In [125]:
apple_price = mul_apple_layer.forward(apple,apple_num)
orange_price = mul_orange_layer.forward(orange,orange_num)
price = add_apple_orange_layer.forward(apple_num,orange_num)
total_price = mul_tax_layer.forward(price,tax)

In [126]:
dout=1
dprice, dtax = mul_tax_layer.backward(dout)

In [127]:
total_price

5.5

In [128]:
dtax

5

In [129]:
dprice

1.1

In [131]:
#dx,dy = add_apple_orange_layer.backward(dprice)
dapple,dorange = add_apple_orange_layer.backward(dprice)

In [135]:
add_apple_orange_layer.backward(dprice)

(1.1, 1.1)

In [132]:
dapple,dapple_num = mul_apple_layer.backward(dapple)
dorange,dorange_num = mul_orange_layer.backward(dorange)

In [133]:
dorange

3.3000000000000003

In [134]:
dorange_num

165.0

In [136]:
def relu(x):
    return np.where(x>0,x,0)

In [156]:
class Relu:
    def __init__(self):
        self.mask = None
        
    def forward(self,x):
        self.mask = (x<=0)
        out = x.copy()
        out[self.mask] = 0
        return out
    
    def backward(self,dout):
        dout[self.mask] = 0
        dx = dout
        return dx

In [138]:
relu_layer = Relu()

In [141]:
x = np.random.randn(4,2)
x

array([[ 1.32463001, -0.79558985],
       [ 1.05389834, -0.93494539],
       [-0.42515072,  0.02432526],
       [-0.80723601, -0.31525857]])

In [143]:
xf = relu_layer.forward(x)
xf

array([[1.32463001, 0.        ],
       [1.05389834, 0.        ],
       [0.        , 0.02432526],
       [0.        , 0.        ]])

In [157]:
xb = relu_layer.backward(xf) ???????
xb

array([[1.32463001, 0.        ],
       [1.05389834, 0.        ],
       [0.        , 0.02432526],
       [0.        , 0.        ]])

In [151]:
x_mask = (x>0)
x_mask

array([[ True, False],
       [ True, False],
       [False,  True],
       [False, False]])

In [182]:
class Sigmoid:
    def __init_(self):
        self.out = None
    
    def forward(self,x):
        out = 1 / (1+np.exp(-x))
        self.out = out
        return out 
    
    def backward(self,dout):
        dx = dout*self.out*(1-self.out)
        return dx

In [183]:
x = np.random.randn(4,2)

In [184]:
sigmoid_layer = Sigmoid()
sf = sigmoid_layer.forward(x)
sb = sigmoid_layer.backward(sf)

In [185]:
sf

array([[0.78783438, 0.20620988],
       [0.57252334, 0.51877713],
       [0.16838897, 0.58223402],
       [0.36379806, 0.52548079]])

In [ ]:
#softmax는 알아서 짜봐 ^^

In [190]:
X = np.random.randn(2)
W = np.random.randn(2,3)
b = np.random.randn(3)
X.shape
W.shape
b.shape    

out = np.dot(X,W) + b #넘파이 중요하다고 말했습니다^^
out.shape

(3,)

In [196]:
W = np.matrix(W)
W_t = np.matrix(W.T)
np.dot(W,W.T)
W*W_t

matrix([[ 0.85408539, -0.18595254],
        [-0.18595254,  1.36350684]])

In [202]:
x = np.array([[0,0,0],[10.,10.,10.]])
b = np.array([1,2,3])
out = x+b

dy = np.arange(1,7).reshape(2,3)
dy

dB = np.sum(dy,axis=0)
dB

array([5, 7, 9])

In [207]:
class Affine:
    def __init__(self,W,b):
        self.W = W
        self.b = b
        self.x = None
        self.dW = None
        self.db = None
        
    def forward(self,x):
        self.x = x
        out = np.dot(x,self.W)+self.b
        
        return out
    
    def backward(self,dout):
        dx = np.dot(dout, self.W)

In [208]:
X = np.random.randn(2,3)
W = np.random.randn(3,2)
out = np.dot(X,W) 

In [210]:
out,W

(array([[ 2.09976048, -2.55220883],
        [ 0.85774643, -1.47768937]]),
 array([[-1.47465077,  1.7278147 ],
        [-1.22368657,  0.71008509],
        [ 0.24088229, -0.01521896]]))

In [211]:
np.dot(out,W)

ValueError: shapes (2,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

In [212]:
np.dot(out,W.T)

array([[-7.50615736, -4.38173413,  0.5446371 ],
       [-3.81804985, -2.09889797,  0.22910483]])

In [213]:
class Affine:
    def __init__(self,W,b):
        self.W = W
        self.b = b
        self.x = None
        self.dW = None
        self.db = None
        
    def forward(self,x): #predict랑 같음
        self.x = x
        out = np.dot(x,self.W)+self.b
        
        return out
    
    def backward(self,dout): #추가
        dx = np.dot(dout, self.W.T)
        self.dW = np.dot(self.x.T,dout)
        self.db = np.sum(dout,axis=0)
        
        return dx

In [214]:
x = np.random.randn(4,2)
W = np.random.randn(2,3)
b = np.random.randn(3,)

In [215]:
affine = Affine(W,b)
out = affine.forward(x)
out

array([[ 2.34092885e-02, -4.24199406e-01,  4.69301649e-01],
       [-2.16837290e+00,  1.51814811e+00, -1.36302381e+00],
       [-2.09288169e+00,  1.70745947e+00, -1.77484264e+00],
       [-1.39435948e-02,  1.91811067e-03, -2.90443479e-01]])

In [217]:
sig = Sigmoid()
sig_out = sig.forward(out)
sig_out

array([[0.50585205, 0.39551231, 0.61521845],
       [0.10262678, 0.82026562, 0.20374929],
       [0.10979061, 0.84650648, 0.14494113],
       [0.49651416, 0.50047953, 0.4278953 ]])

In [218]:
out.shape

(4, 3)

In [223]:
affine.backward(out)
affine.dW
affine.db

array([-4.25178889,  2.80332629, -2.95900829])

In [229]:
#소프트맥스 함수
x = np.random.randn(5,3)
w1 = np.random.randn(3,4)
b1 = np.random.randn(4)
w2 = np.random.randn(4,3)
b2 = np.random.randn(3)
t = np.zeros((5,3))
t[:,1]=1

from loss import cross_entropy_error
from activation import softmax
def relu(x):
    return np.maximum(0,x)
l1 = np.dot(x,w1)+b1
z1 = relu(l1)
l2 = np.dot(z1,w2)+b2

cross_entropy_error(softmax(l2),t)

2.883662195834364

In [231]:
class SoftmaxWithLoss:
    def __init__(self):
        self.loss = None
        self.y = None
        self.t = None
    
    def forward(self,x,t):
        self.y = softmax(x) #self.predict(x)
        self.t = t
        self.loss = cross_entropy_error(self.y,self.t)
        return self.loss
    
    def backward(self,dout=1):
        dx = dout*(self.y-self.t)/y.shape[0]
        return dx

In [234]:
dL = SoftmaxWithLoss()
dLforward = dL.forward(l2,t)
dLforward

2.883662195834364

In [236]:
dL.backward().shape

(5, 3)

In [237]:
l2.shape

(5, 3)